version: "3.7"

services:
    web:
        image: pws-portfolio
        container_name: pws-portfolio
        restart: unless-stopped
        ports:
          - "3000:80"
        build:
            context: ./client
            dockerfile: Dockerfile