version: '3.8'

container_name: carlospomares.es
services:
    server:
        image: carlospomares-server
        container_name: cp-server
        build:
            context: ./server
            dockerfile: Dockerfile
        depends_on:
            - web
        port:
            - "80:80"
    web:
        image: carlospomares-web
        container_name: cp-web
        expose:
            - 3000
        environment: 
            - NODE_ENV=
            - MAIL=
        build:
            context: ./client
            dockerfile: Dockerfile
        depends_on:
            - api
    api:
        image: carlospomares-api
        container_name: cp-api
        expose:
            - "3000"
        environment: 
            - NODE_ENV=
            # GLOBAL
            - HOSTNAME=
            - PORT=
            - CERT_KEY=
            - CERT_SECRET=
            # MAIL
            - MAIL_HOST=
            - MAIL_PORT=
            - MAIL_TYPE=
            # MAIL AUTH
            - MAIL_USER=
            - MAIL_CLIENTID=
            - MAIL_CLIENTSECRET=
            - MAIL_REFRESHTOKEN=
            - MAIL_PROCESSTOKEN=
            # MAIL MESSAGE
            - MAIL_FROM=
            - MAIL_TO=
            - MAIL_SUBJECT=
        build:
            context: ./api
            dockerfile: Dockerfile